name: Build and deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.15.2

      - name: Build
        run: zig build run --prefix zig-out

      - name: Remove bin directory
        run: rm -rf zig-out/bin

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
